apiVersion: apps/v1beta1
kind: Deployment
metadata: {name: back}
spec:
  replicas: 1
  template:
    metadata:
      labels: {app: back}
    spec:
      containers:
      - image: gcr.io/bh-org-01/mojp-dbs-back:104b9eb86703221e2440082ae253b6521c9c9f91
        name: back
        ports:
        - {containerPort: 80}
        - {containerPort: 8081}
        resources:
          requests: {cpu: 20m}
        volumeMounts:
        - {mountPath: /etc/bhs, name: etc-bhs, readOnly: true}
      volumes:
      - name: etc-bhs
        secret: {secretName: etc-bhs}
---
apiVersion: v1
kind: Service
metadata: {name: back}
spec:
  ports:
  - {name: '80', port: 80}
  - {name: '8081', port: 8081}
  selector: {app: back}
