apiVersion: apps/v1beta1
kind: Deployment
metadata: {name: "back"}
spec:
  replicas: 1
  strategy: {type: "Recreate"}
  template:
    metadata: {labels: {app: "back"}}
    spec:
      containers:
      - name: back
        image: orihoch/mojp-dbs-back
        ports: [{containerPort: 80}, {containerPort: 8081}]
        resources: {requests: {cpu: "20m"}}
        # each secret's key will be a filename under /etc/bhs
        volumeMounts: [{name: "etc-bhs", mountPath: "/etc/bhs", readOnly: true}]
      restartPolicy: Always
      volumes: [{name: "etc-bhs", secret: {secretName: "etc-bhs"}}]
---
apiVersion: v1
kind: Service
metadata: {name: "back"}
spec:
  selector: {app: "back"}
  ports: [{name: "80", port: 80}, {name: "8081", port: 8081}]
