apiVersion: apps/v1beta1
kind: Deployment
metadata: {name: front}
spec:
  replicas: 1
  template:
    metadata:
      labels: {app: front}
    spec:
      containers:
      - image: gcr.io/bh-org-01/mojp-dbs-front:375e9865c843ee65b931153bb04ea79aaa62064d
        name: front
        ports:
        - {containerPort: 80}
        resources:
          requests: {cpu: 20m}
        volumeMounts:
        - {mountPath: /etc/bhs, name: etc-bhs, readOnly: true}
      volumes:
      - name: etc-bhs
        secret: {secretName: etc-bhs}
---
apiVersion: v1
kind: Service
metadata: {name: front}
spec:
  ports:
  - {name: '80', port: 80}
  selector: {app: front}
