apiVersion: apps/v1beta1
kind: Deployment
metadata: {name: front}
spec:
  replicas: 1
  template:
    metadata:
      labels: {app: front}
    spec:
      containers:
      - image: orihoch/mojp-dbs-front@sha256:a316c768c012988c0c376ba22806772ebdbc02c6c9247e4e3a5fa2554a99b0d7
        name: front
        ports:
        - {containerPort: 80}
        resources:
          requests: {cpu: 20m}
        volumeMounts:
        - {mountPath: /etc/bhs, name: etc-bhs, readOnly: true}
      volumes:
      - name: etc-bhs
        secret: {secretName: etc-bhs}
---
apiVersion: v1
kind: Service
metadata: {name: front}
spec:
  ports:
  - {name: '80', port: 80}
  selector: {app: front}
