apiVersion: apps/v1beta1
kind: Deployment
metadata: {name: "front"}
spec:
  replicas: 1
  template:
    metadata: {labels: {app: "front"}}
    spec:
      containers:
      - name: front
        # https://github.com/Beit-Hatfutsot/dbs-front/releases/tag/0.14.0
        image: gcr.io/bh-org-01/mojp-dbs-front:25674d9cddcf97db385a6a15ea53ab5287893c3a
        ports: [{containerPort: 80}]
        resources: {requests: {cpu: "20m"}}
        # each secret's key will be a filename under /etc/bhs
        volumeMounts: [{name: "etc-bhs", mountPath: "/etc/bhs", readOnly: true}]
      volumes: [{name: "etc-bhs", secret: {secretName: "etc-bhs"}}]
---
apiVersion: v1
kind: Service
metadata: {name: "front"}
spec:
  selector: {app: "front"}
  ports: [{name: "80", port: 80}]
