apiVersion: apps/v1beta1
kind: Deployment
metadata: {name: "nginx"}
spec:
  replicas: 1
  template:
    metadata: {labels: {app: "nginx"}}
    spec:
      containers:
      - name: nginx
        image: gcr.io/bh-org-01/mojp-dbs-nginx:93d7fb97bff58fd61892a90f4f8c2edf7c7b1259
        resources: {requests: {cpu: "20m"}}
        ports: [{containerPort: 80}, {containerPort: 443}]
---
apiVersion: v1
kind: Service
metadata: {name: "nginx"}
spec:
  type: LoadBalancer
  selector: {app: "nginx"}
  ports: [{name: "80", port: 80}, {name: "443", port: 443}]
