apiVersion: apps/v1beta1
kind: Deployment
metadata: {name: "nginx"}
spec:
  replicas: 1
  template:
    metadata: {labels: {app: "nginx"}}
    spec:
      containers:
      - name: nginx
        image: gcr.io/bh-org-01/mojp-dbs-nginx:a6a285fd95b994774aed64bdb4330ce5aee7d1b6
        resources: {requests: {cpu: "20m"}}
        ports: [{containerPort: 80}, {containerPort: 443}]
        volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html
        - name: nginx-conf-d
          mountPath: /etc/nginx/conf.d
        - name: letsencrypt-etc
          mountPath: /letsencrypt-etc
      volumes:
      - name: nginx-html
        hostPath:
          path: /var/mojp/nginx-html
      - name: nginx-conf-d
        configMap: {name: "nginx-conf-d"}
      - name: letsencrypt-etc
        hostPath:
          path: /var/mojp/letsencrypt-etc
---
apiVersion: v1
kind: Service
metadata: {name: "nginx"}
spec:
  type: LoadBalancer
  selector: {app: "nginx"}
  ports: [{name: "80", port: 80}, {name: "443", port: 443}]
