apiVersion: v1
kind: Service
metadata:
  name: pipelines
spec:
  ports:
  - port: 5000
  selector:
    app: pipelines
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pipelines
spec:
  replicas: 1
  strategy: {type: Recreate}
  template:
    metadata:
      labels:
        app: pipelines
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: pool-3
      containers:
      - name: pipelines
        image: gcr.io/bh-org-01/orihoch-dbs-back-pipelines:f36618e2fdb61813ef0fb473bd85d1f11437ee3b
        args: ["server"]
        ports:
        - containerPort: 5000
        env:
        - {name: "S3_BUCKET_PREFIX", value: ""}
        - {name: "AWS_ACCESS_KEY_ID", valueFrom: {secretKeyRef: {name: "env-vars", key: "MINIO_ACCESS_KEY"}}}
        - {name: "AWS_SECRET_ACCESS_KEY", valueFrom: {secretKeyRef: {name: "env-vars", key: "MINIO_SECRET_KEY"}}}
        - {name: "S3_ENDPOINT_URL", value: "http://minio:9000"}
        - {name: "SITEMAP_ES_HOST", value: "bhs-prod-db"}
        - {name: "SITEMAP_ES_INDEX", value: "mojp-prod"}
        resources:
          requests:
            cpu: "0.1"
            memory: "10Mi"
